name: share_utils_platform_interface
description: A common platform interface for the share_utils flutter plugin
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


